IMU_RAW_TOPIC: "/camera/imu"
IMU_FILTERED_TOPIC: "/kf/imu"
L_MOTOR_RATE_TOPIC: "/speed1"
R_MOTOR_RATE_TOPIC: "/speed2"
FILTER_TYPE: "ekf" # Either "ukf" or "ekf"

KF_INITIAL_STATE:
  [
    -0.025876251,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.165,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
  ]

KF_INITIAL_STATE_COVAR:
  [
    1.0,
    1.0,
    1.0,
    1.0,
    1.0,
    1.0,
    1.0,
    1.0,
    1.0,
    1.0,
    1.0,
    1.0,
    1.0,
    1.0,
  ]
KF_INITIAL_STATE_COVAR_COEFF: 0.02
KF_PROC_COVAR:
  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
KF_PROC_COVAR_COEFF: 0.002
KF_OBS_COVAR: [10, 10, 10, 1, 1, 1]
KF_OBS_COVAR_COEFF: 0.05
