IMU_RAW_TOPIC: "/camera/imu"
IMU_FILTERED_TOPIC: "/kf/imu"
L_MOTOR_RATE_TOPIC: "/speed1"
R_MOTOR_RATE_TOPIC: "/speed2"
KALMAN_STATE_TOPIC: "/kf/state"
LOOP_RATE: 400
KF_PUB_RATE: 10
FILTER_TYPE: "ekf" # Either "ukf" or "ekf"

KF_INITIAL_STATE:
  [
    -0.025876251,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.165,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
  ]

KF_INITIAL_STATE_COVAR:
  [
    0.01,
    0.01,
    0.01,
    0.01,
    0.01,
    0.01,
    0.01,
    0.01,
    0.01,
    0.01,
    0.01,
    0.01,
    0.01,
    0.01,
  ]
KF_INITIAL_STATE_COVAR_COEFF: 1.0
KF_PROC_COVAR:
  [0, 0, 0, 0, 0, 0, 0, 0, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001]
KF_PROC_COVAR_COEFF: 1.0
KF_OBS_COVAR: [0.2, 0.2, 0.2, 0.2, 0.2, 0.2]
KF_OBS_COVAR_COEFF: 10
